from influxdb import SeriesHelper

from HomematicToInflux.data_types import DeviceType

class FALMOTC12StateSeriesHelper(SeriesHelper):
    class Meta:
        client = None

        # The series name must be a string. Add dependent fields/tags
        # in curly brackets.
        series_name = 'stateFALMOTC12'

        device_type = DeviceType.FALMOTC12.value

        fields = [
            'CONFIG_PENDING_0',
            'DATE_TIME_UNKNOWN_0',
            'DUTY_CYCLE_0',
            'HEATING_COOLING_0',
            'HUMIDITY_ALARM_0',
            'OPERATING_VOLTAGE_0',
            'OPERATING_VOLTAGE_STATUS_0',
            'RSSI_DEVICE_0',
            'RSSI_PEER_0',
            'TEMPERATURE_LIMITER_0',
            'UNREACH_0',
            'UPDATE_PENDING_0',
            'DEW_POINT_ALARM_1',
            'EMERGENCY_OPERATION_1',
            'EXTERNAL_CLOCK_1',
            'FROST_PROTECTION_1',
            'HUMIDITY_LIMITER_1',
            'LEVEL_1',
            'LEVEL_STATUS_1',
            'VALVE_STATE_1',
            'DEW_POINT_ALARM_2',
            'EMERGENCY_OPERATION_2',
            'EXTERNAL_CLOCK_2',
            'FROST_PROTECTION_2',
            'HUMIDITY_LIMITER_2',
            'LEVEL_2',
            'LEVEL_STATUS_2',
            'VALVE_STATE_2',
            'DEW_POINT_ALARM_3',
            'EMERGENCY_OPERATION_3',
            'EXTERNAL_CLOCK_3',
            'FROST_PROTECTION_3',
            'HUMIDITY_LIMITER_3',
            'LEVEL_3',
            'LEVEL_STATUS_3',
            'VALVE_STATE_3',
            'DEW_POINT_ALARM_4',
            'EMERGENCY_OPERATION_4',
            'EXTERNAL_CLOCK_4',
            'FROST_PROTECTION_4',
            'HUMIDITY_LIMITER_4',
            'LEVEL_4',
            'LEVEL_STATUS_4',
            'VALVE_STATE_4',
            'DEW_POINT_ALARM_5',
            'EMERGENCY_OPERATION_5',
            'EXTERNAL_CLOCK_5',
            'FROST_PROTECTION_5',
            'HUMIDITY_LIMITER_5',
            'LEVEL_5',
            'LEVEL_STATUS_5',
            'VALVE_STATE_5',
            'DEW_POINT_ALARM_6',
            'EMERGENCY_OPERATION_6',
            'EXTERNAL_CLOCK_6',
            'FROST_PROTECTION_6',
            'HUMIDITY_LIMITER_6',
            'LEVEL_6',
            'LEVEL_STATUS_6',
            'VALVE_STATE_6',
            'DEW_POINT_ALARM_7',
            'EMERGENCY_OPERATION_7',
            'EXTERNAL_CLOCK_7',
            'FROST_PROTECTION_7',
            'HUMIDITY_LIMITER_7',
            'LEVEL_7',
            'LEVEL_STATUS_7',
            'VALVE_STATE_7',
            'DEW_POINT_ALARM_8',
            'EMERGENCY_OPERATION_8',
            'EXTERNAL_CLOCK_8',
            'FROST_PROTECTION_8',
            'HUMIDITY_LIMITER_8',
            'LEVEL_8',
            'LEVEL_STATUS_8',
            'VALVE_STATE_8',
            'DEW_POINT_ALARM_9',
            'EMERGENCY_OPERATION_9',
            'EXTERNAL_CLOCK_9',
            'FROST_PROTECTION_9',
            'HUMIDITY_LIMITER_9',
            'LEVEL_9',
            'LEVEL_STATUS_9',
            'VALVE_STATE_9',
            'DEW_POINT_ALARM_10',
            'EMERGENCY_OPERATION_10',
            'EXTERNAL_CLOCK_10',
            'FROST_PROTECTION_10',
            'HUMIDITY_LIMITER_10',
            'LEVEL_10',
            'LEVEL_STATUS_10',
            'VALVE_STATE_10',
            'DEW_POINT_ALARM_11',
            'EMERGENCY_OPERATION_11',
            'EXTERNAL_CLOCK_11',
            'FROST_PROTECTION_11',
            'HUMIDITY_LIMITER_11',
            'LEVEL_11',
            'LEVEL_STATUS_11',
            'VALVE_STATE_11',
            'DEW_POINT_ALARM_12',
            'EMERGENCY_OPERATION_12',
            'EXTERNAL_CLOCK_12',
            'FROST_PROTECTION_12',
            'HUMIDITY_LIMITER_12',
            'LEVEL_12',
            'LEVEL_STATUS_12',
            'VALVE_STATE_12',
        ]

        tags = ['DEVICE_NAME']

        bulk_size = 5
        autocommit = True

